### ISSUE TITLE
Make each function configurable independently

### ISSUE THREAD

**Issue by Omgise** [Lachrymogenic/Lachryvisions#1]
This allows you to disable features you don't want

**Comment by Lachrymogenic** [comment]
Might have issues with multiplayer (which i dont even know if it works)
but was planning on doing that.

**Comment by Lachrymogenic** [comment]
I am a beginner and this was just a repo I made because I wanted to add a few things to 1.7.10 but I guess I'll start looking into it now. I have no idea how to create mod options though and YouTube just has 0 tutorials for these kinds of things, but I have free time so, if I can figure it out, you might see an update come out today.

**Comment by Lachrymogenic** [comment]
What kind of features do you think should be toggleable?

**Comment by Lachrymogenic** [comment]
i got it working btw
![image](https://github.com/Lachrymogenic/Lachryvisions/assets/160751404/9d5f9791-7579-41e5-99e3-bafae7ed16f9)

**Comment by Lachrymogenic** [comment]
Figured out how categories work
![image](https://github.com/Lachrymogenic/Lachryvisions/assets/160751404/4abbce36-a7de-4f6a-9f86-e24e6e0ca416)

**Comment by Lachrymogenic** [comment]
Certain features like Custom Items and Blocks will be under simple toggles for now because there's not that many stuff that I have added yet. In the future there will be and they will all get their own individual toggles. This seems like it should be fine for now.
